[package]
name = "tiangong-plugin-generate-video"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

[dependencies]
tiangong-core = { workspace = true }
tiangong-media = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
