[package]
name = "tiangong-plugin-generate-image-openai-wasm"
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"
description = "Generate-Image-OpenAI 插件的 WASM 组件"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
tiangong-plugin-generate-image-openai-protocol = { workspace = true }
wit-bindgen = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
