[package]
name = "tiangong-llm"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[dependencies]
tiangong-anthropic = { workspace = true }
tiangong-types = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
async-openai = { workspace = true, features = ["byot", "chat-completion", "model"] }
backoff = { workspace = true }
tokio = { workspace = true, features = ["rt", "time"] }
reqwest = { workspace = true, default-features = false, features = ["json", "rustls"] }
futures-util = { workspace = true }
tracing = { workspace = true }
