[package]
name = "tiangong-memory"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[features]
default = []

[dependencies]
tokio = { workspace = true, features = [
    "sync",
    "time",
    "fs",
    "rt",
    "net",
    "io-util",
    "macros",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true, default-features = false, features = [
    "std",
    "clock",
] }
scru128 = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
rusqlite = { workspace = true, features = [
    "bundled-sqlcipher-vendored-openssl",
] }
sha2 = { workspace = true }
hex = { workspace = true }
tantivy = { workspace = true }
libc = { workspace = true }
tiangong-llm = { workspace = true }
tiangong-types = { workspace = true }
lancedb = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
tempfile = { workspace = true }
tiangong-config = { workspace = true }
tiangong-core = { workspace = true }
