[package]
name = "tiangong-plugin-skill"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

[dependencies]
tiangong-core = { workspace = true }
tiangong-types = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
