app = "tiangong"
identifier = "io.silent.tiangong"
version = "0.1.0"

[linux]
format = "tar.gz"
icon = "assets/icons/silent-logo.png"
out_dir = "output/release"

[macos]
format = "dmg"
icon = "assets/icons/silent-logo.icns"
out_dir = "output/release"

[updater]
mode = "embedded"

[windows]
format = "zip"
icon = "assets/icons/silent-logo.png"
out_dir = "output/release"
