[package]
name = "tiangong-scheduler"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
cron = { workspace = true }
scru128 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
dirs = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
