[package]
name = "tiangong-plugin-speech-to-text-wasm"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Speech-To-Text 插件的 WASM 组件"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
tiangong-plugin-speech-to-text-protocol = { workspace = true }
wit-bindgen = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
