[package]
name = "tiangong-plugin-generate-image"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

[dependencies]
tiangong-core = { workspace = true }
tiangong-llm = { workspace = true }
tiangong-config = { workspace = true }
tiangong-media-archive = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
