[package]
name = "tiangong-plugin-memory-wasm"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
description = "Memory 插件的 WASM 组件"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
tiangong-plugin-memory-protocol = { workspace = true }
tiangong-types = { workspace = true }
wit-bindgen = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
scru128 = { workspace = true }
