[package]
name = "tiangong-server"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[dependencies]
tiangong-app-state = { workspace = true }
tiangong-core = { workspace = true }
tiangong-llm = { workspace = true }
tiangong-plugin-command = { workspace = true }
tiangong-plugin-fetch = { workspace = true }
tiangong-plugin-fs = { workspace = true }
tiangong-plugin-generate-image = { workspace = true }
tiangong-plugin-generate-video = { workspace = true }
tiangong-plugin-speech-to-text = { workspace = true }
tiangong-plugin-runtime = { workspace = true }
tiangong-plugin-task = { workspace = true }
tiangong-plugin-analyze-attachment = { workspace = true }
tiangong-plugin-skill-protocol = { workspace = true }
tiangong-plugin-mcp-protocol = { workspace = true }
tiangong-plugin-agent-team = { workspace = true }
tiangong-plugin-prompt = { workspace = true }
tiangong-config = { workspace = true }
tiangong-media = { workspace = true }
tiangong-media-archive = { workspace = true }
tiangong-types = { workspace = true }
tiangong-scheduler = { workspace = true }
async-trait = { workspace = true }
silent = { workspace = true, features = ["upgrade", "scheduler"] }
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "fs", "time"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
async-channel = { workspace = true }
async-lock = { workspace = true }
scru128 = { workspace = true }
chrono = { workspace = true }
hmac = { workspace = true }
hex = { workspace = true }
http-body-util = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["rustls"] }
dirs = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
