[package]
name = "tiangong-plugin-terminal"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
links = "terminal"

[dependencies]
tiangong-config = { workspace = true }
tiangong-core = { workspace = true }
tiangong-toolkit = { workspace = true }
tiangong-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "sync", "process", "io-util"] }
tauri = { workspace = true, features = ["unstable"] }
portable-pty = "0.8"
scru128 = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
descape = "3"
strip-ansi-escapes = "0.2"
vte = "0.14"
tempfile = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
