[package]
name = "tiangong-plugin-mcp-wasm"
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"
description = "MCP 插件的 WASM 组件"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
tiangong-plugin-mcp-protocol = { workspace = true }
wit-bindgen = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
