[package]
name = "tiangong-cli"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[dependencies]
tiangong-app-state = { workspace = true }
tiangong-core = { workspace = true }
tiangong-llm = { workspace = true }
tiangong-plugin-command = { workspace = true }
tiangong-plugin-fs = { workspace = true }
tiangong-plugin-runtime = { workspace = true }
tiangong-plugin-task = { workspace = true }
tiangong-plugin-skill-protocol = { workspace = true }
tiangong-plugin-mcp-protocol = { workspace = true }
tiangong-plugin-agent-team = { workspace = true }
tiangong-config = { workspace = true }
tiangong-types = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
anyhow = { workspace = true }
scru128 = { workspace = true }
serde_json = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
termimad = { workspace = true }
