[package]
name = "tiangong-cli"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[dependencies]
tiangong-core = { workspace = true }
tiangong-memory = { workspace = true }
tiangong-plugin-command = { workspace = true }
tiangong-plugin-fetch = { workspace = true }
tiangong-plugin-fs = { workspace = true }
tiangong-plugin-index = { workspace = true }
tiangong-plugin-generate-image = { workspace = true }
tiangong-plugin-generate-video = { workspace = true }
tiangong-plugin-text-to-speech = { workspace = true }
tiangong-plugin-speech-to-text = { workspace = true }
tiangong-plugin-memory = { workspace = true }
tiangong-plugin-scheduler = { workspace = true }
tiangong-plugin-task = { workspace = true }
tiangong-plugin-analyze-attachment = { workspace = true }
tiangong-plugin-skill = { workspace = true }
tiangong-plugin-mcp = { workspace = true }
tiangong-config = { workspace = true }
tiangong-types = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
termimad = { workspace = true }
