[package]
name = "tiangong-media"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["json", "rustls", "multipart"] }
tokio = { workspace = true, features = ["sync"] }
