[package]
name = "tiangong-plugin-browser"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
links = "browser"

[dependencies]
tiangong-core = { workspace = true }
tiangong-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "sync"] }
tauri = { workspace = true, features = ["unstable"] }
base64-url = "2"
scru128 = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
